# Registers a hidden Scheduled Task: Chrome (CDP) + Most agent at logon.
# Chrome starts minimized; agent logs to %LOCALAPPDATA%\Most\logs\agent.log
param(
    [string]$ProjectRoot = "C:\projects\most.neeklo.ru",
    [string]$TaskName = "MostAgent",
    [int]$LogonDelaySec = 45
)

$ErrorActionPreference = "Stop"

$launcher = Join-Path $ProjectRoot "deploy\windows\agent-launch.vbs"
if (-not (Test-Path $launcher)) {
    Write-Error "Missing $launcher"
    exit 1
}

# Write launcher with the correct project path (VBS has no env vars at logon).
$vbsContent = @"
' Auto-generated by install-agent-autostart.ps1 — do not edit by hand.
Set shell = CreateObject("WScript.Shell")
projectRoot = "$($ProjectRoot -replace '\\', '\\')"

shell.Run "powershell -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & projectRoot & "\deploy\windows\start-chrome-debug.ps1"" -Stealth", 0, False
WScript.Sleep 10000
shell.Run "powershell -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & projectRoot & "\deploy\windows\open-messenger-tabs.ps1"" -Stealth -ProjectRoot """ & projectRoot & """", 0, False
WScript.Sleep 3000
shell.Run "powershell -ExecutionPolicy Bypass -WindowStyle Hidden -File """ & projectRoot & "\deploy\windows\start-agent.ps1"" -Silent -ProjectRoot """ & projectRoot & """", 0, False
"@
Set-Content -Path $launcher -Value $vbsContent -Encoding ASCII

$action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$launcher`""
$trigger = New-ScheduledTaskTrigger -AtLogOn -RandomDelay (New-TimeSpan -Seconds 30)
if ($LogonDelaySec -gt 0) {
    $trigger.Delay = "PT${LogonDelaySec}S"
}
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RestartCount 999 `
    -RestartInterval (New-TimeSpan -Minutes 2) `
    -ExecutionTimeLimit (New-TimeSpan -Days 3650)
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Limited

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null

Write-Host "Scheduled task '$TaskName' installed." -ForegroundColor Green
Write-Host "  Project: $ProjectRoot" -ForegroundColor Cyan
Write-Host "  Logon delay: ${LogonDelaySec}s (no window flash during boot)" -ForegroundColor Cyan
Write-Host "  Agent log: $env:LOCALAPPDATA\Most\logs\agent.log" -ForegroundColor Cyan
Write-Host "  Chrome: minimized, separate profile, CDP :9222" -ForegroundColor Cyan
